### ISSUE TITLE
white rabbit lcd images not matching

### ISSUE THREAD

**Issue by NeonLightning** [roodriiigooo/PWNAGOTCHI-CUSTOM-FACES-MOD#10]
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/dist-packages/pwnagotchi/identity.py", line 59, in __init__
>     self._view.on_starting()
>   File "/usr/local/lib/python3.9/dist-packages/pwnagotchi/ui/view.py", line 159, in on_starting
>     self.update()
>   File "/usr/local/lib/python3.9/dist-packages/pwnagotchi/ui/view.py", line 399, in update
>     lv.draw(self._canvas, drawer)
>   File "/usr/local/lib/python3.9/dist-packages/pwnagotchi/ui/components.py", line 73, in draw
>     canvas.paste(self.image, self.xy)
>   File "/usr/lib/python3/dist-packages/PIL/Image.py", line 1517, in paste
>     self.im.paste(im, box)
> ValueError: images do not match

i'm getting this error using them

**Comment by NeonLightning** [comment]
was a tweak_view issue
